# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[profile.default]
solc_version = '0.8.16'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
fuzz_runs = 1_000
remappings = [
  "forge-std=lib/forge-std/src/",
  "solmate=lib/solmate/src/",
  "v3-core=lib/v3-core",
  "v3-periphery=lib/v3-periphery/contracts",
  "openzeppelin-contracts=lib/openzeppelin-contracts/contracts",
  # // "@uniswap/v3-core/=/Users/samuel/.brownie/packages/Uniswap/uniswap-v3-core@1.0.0",
  "@uniswap/v3-core/=lib/v3-core",
  "@openzeppelin=lib/openzeppelin-contracts",
  "util-contracts=lib/util-contracts/contracts",
]

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
